on:
  pull_request:
    branches: ["*"]
  push:
    branches: [master]

env:
  VERSION_OTP: '24.x'
  VERSION_ELIXIR: '1.12.x'

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Build / typecheck / run tests
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        id: beam
        with:
          otp-version: ${{ env.VERSION_OTP }}
          elixir-version: ${{ env.VERSION_ELIXIR }}
      - run: mix do deps.get, deps.compile
      - uses: actions/cache@v2
        id: plt-cache
        with:
          path: |
            _build/dev/*.plt
            _build/dev/*.plt.hash
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
          restore-keys: |
            ${{ runner.os }}-${{ steps.beam.outputs.elixir-version }}-${{ steps.beam.outputs.otp-version }}-plt
      - run: mix dialyzer --plt
        if: steps.plt-cache.outputs.cache-hit != 'true'
      - run: mix dialyzer
      - run: mix test
